spring:
  aop:
    proxy-target-class: true
  application:
    name: api-gateway-zuul-2
    
server:
  port: 8765

eureka:
  instance:
      hostname: localhost
      non-secure-port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.non-secure-port}/eureka/

zuul:
  routes:
    uaa-service:
      sensitiveHeaders:
      path: /uaa/**
      stripPrefix: false
  add-proxy-headers: true

security:
  oauth2:
    sso:
      loginPath: /login
    client:
      accessTokenUri: http://uaa-service/uaa/oauth/token
      userAuthorizationUri: /uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      jwt:
        keyValue: "abc"
      id: openid
      serviceId: ${PREFIX:}resource

logging:
  level.org.springframework.security: DEBUG

# http://localhost:8080/login